name: Code Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  code-checker:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Cppcheck
      run: sudo apt-get -y install cppcheck

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install code checker
      run: pip install setuptools codechecker

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Run code checker
      env:
        CODECHECKER_LOGFILE: ${{github.workspace}}/build/compile_commands.json
        SOURCE_CODE_ROOT_DIR: ${{github.workspace}}/lux_sp
        PARALLEL: 2
      run: ./scripts/run_codechecker.sh

