name: Coverity Scan

on:
  push:
    branches: [coverity_scan]

env:
  BUILD_TYPE: Debug

jobs:
  coverity-scan:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - run: cmake -S ${{github.workspace}}
    - uses: vapier/coverity-scan-action@v1
      with:
        # command: 'make' # default: 'make'
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}

