name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  unit-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install gcovr
      run: sudo apt-get install gcovr

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_CODECOVERAGE=on

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Run gcovr
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --target run-gcovr

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        fail_ci_if_error: true
        files: ./gcovr/cobertura.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

